### ISSUE TITLE
Embedding images into Training leads to a broken image

### ISSUE THREAD

**Issue by Xero28** [EvChurch/my-team-church#46]
**Describe the bug**
I pasted an image into the Training section of a role, and after trying to view the training in my normal profile, the image was blank, and checking it in the editable Training section under Departments, the image was broken.

**To Reproduce**
1. Go to the Training of any role under Departments/Teams
2. Paste an image into the Training.
3. Try to view the Training under Profile

**Expected behavior**
The image to be properly embedded.
Right now, I am resorting to using links to try to get the image inside the Training section.

**Screenshots**
![image](https://user-images.githubusercontent.com/46945554/56070672-4f3c0580-5ddd-11e9-8cdd-186eda40ec4b.png)
![image](https://user-images.githubusercontent.com/46945554/56070676-5400b980-5ddd-11e9-9834-cd87d47f85d3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by Xero28** [comment]
Was waiting on some AWS credentials from Rowan, but now have them. Moving back to "To Do". Priority to get this done by the Training Day.

**Comment by ardation** [comment]
All fixed.
