### ISSUE TITLE
Cannot sign up with email invite, says email already taken

### ISSUE THREAD

**Issue by storyworks** [EvChurch/my-team-church#70]
**Describe the bug**
Email already taken

**To Reproduce**
1) Send pre-created user the email invite
1) clicked email invite and sign up
2) Console shows that email is already taken

**Screenshots**
![image](https://user-images.githubusercontent.com/10802634/59558964-a9617d00-9051-11e9-8f6a-40e3f1f65c50.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Comment by Xero28** [comment]
See #52 and #64

**Comment by Xero28** [comment]
@ZY-L , apparently this should be fixed. I'm going to send you another email invite. Could you please follow the link and try to sign up? And then pass or fail the QA based on the result? Thanks!

**Comment by Xero28** [comment]
Oh wait, never mind; it seems like you have an account now? @ZY-L, can you confirm that you can log in to your account?
