### ISSUE TITLE
New "Forgot Password" option when signing in

### ISSUE THREAD

**Issue by Xero28** [EvChurch/my-team-church#72]
**Is your feature request related to a problem? Please describe.**
If you were to forget your password, there is no way for the User to reset their password, without just asking Tatai.

**Describe the solution you'd like**
An option to say "Forgot Password" and reset it on the login page.

**Comment by ardation** [comment]
# QA Forgot Password
- go to app.myteam.church (sign out if signed in)
- click on forgot password
- type in email address and click submit
- go to email and click link in email
- change password (make sure password is same in confirm box)
- log in with changed password
- check email received saying that you recently changed your password

# QA Update Password
- go to app.myteam.church and sign in
- click on menu on top right and go to update password
- type in wrong current password and type in new password with confirm
- error should display
- update current password to correct one
- submit
- sign out
- log in with changed password
- check email received saying that you recently changed your password

**Comment by Xero28** [comment]
Testing it now.

**Comment by Xero28** [comment]
Forgot Password has passed QA.

**Comment by Xero28** [comment]
Update Password has passed QA.
